version: "{build}"

# Uncomment to debug via RDP
# init:
#   - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  NODE_VERSION: 6.11.2
  MONGO_VERSION: "3.2.9"

install:
  # Install Node.js
  - ps: Install-Product node $env:NODE_VERSION x64
  # Install MongoDB with SSL
  - ps: >-
      Write-Host "Uninstalling old MongoDB..."

      msiexec.exe /qn /x `{FE313923-51D6-4FF6-AAF6-A78BEE1AF868`}

      rm -r c:\mongodb

      Write-Host "Installing MongoDB $env:MONGO_VERSION with SSL..."

      $msiPath = "$($env:USERPROFILE)\mongodb-win32-x86_64-2008plus-ssl-$($env:MONGO_VERSION)-signed.msi"

      (New-Object Net.WebClient).DownloadFile("https://fastdl.mongodb.org/win32/mongodb-win32-x86_64-2008plus-ssl-$($env:MONGO_VERSION)-signed.msi", $msiPath)

      cmd /c start /wait msiexec /q /i $msiPath INSTALLLOCATION=C:\mongodb ADDLOCAL="all"

      del $msiPath

      mkdir c:\mongodb\data\db | Out-Null

      mkdir c:\mongodb\log | Out-Null

      Write-Host "Writing configuration..."

      "systemLog:
        destination: file
        path: c:\mongodb\log\mongod.log
      storage:
        dbPath: c:\mongodb\data\db
      net:
        ssl:
          mode: requireSSL
          PEMKeyFile: c:\projects\$($env:APPVEYOR_PROJECT_NAME)\tls\cert-key-combined.pem
      " | Out-File C:\mongodb\mongod.cfg -Encoding utf8

      Write-Host "Starting service..."

      cmd /c start /wait sc create MongoDB binPath= "C:\mongodb\bin\mongod.exe --service --config=C:\mongodb\mongod.cfg" DisplayName= "MongoDB" start= "demand"

      Start-Service mongodb

build: off

test_script:
  - npm install
  - npm install -g roboter-cli
  - npm run bot
